name: fire_control_app
description: 智慧消防移动端
publish_to: 'none'

version: 2.0.0+4

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  date_format: ^2.0.7
  animations: ^2.0.7
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  umeng_push_sdk: ^2.0.0
  stomp_dart_client: ^0.4.4
  logger: ^1.2.2
  package_info_plus: ^3.0.3
  overlay_support: ^2.1.0
  just_audio: ^0.9.32
  intl: ^0.17.0
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/media/
  fonts:
   - family: fcm
     fonts:
       - asset: assets/fonts/iconfont.ttf
