name: fire_control_app
description: 智慧消防移动端
publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  date_format: ^2.0.7
  animations: ^2.0.7
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.17
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
   - family: fcm
     fonts:
       - asset: assets/fonts/iconfont.ttf
